dataset:
  name: vggface2
  required_disk_gib: 150

  source:
    provider: kaggle-cli
    dataset_handle: hearfool/vggface2

  paths:
    download_dir: data/downloads/vggface2
    raw_dir: data/raw/vggface2

  extraction:
    enabled: true
    remove_archive_after_extract: false

  validation:
    enabled: true
    minimum_image_count: 3000000
    minimum_identity_count: 9000

    image_extensions:
      - .jpg
      - .jpeg
      - .png
